In [ ]:
#Assignment 4
#Addition subtraction  on matrices

In [13]:
matrix_1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
matrix_2 = [
    [10,11,12],
    [13,14,15],
    [16,17,19]
]
result = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

#result for addition subtraction and multiplication
print("The martix_1 is:")
for col_1 in matrix_1 :
    print(col_1)

print("The matrix_2 is:")
for col_2 in matrix_2:
    print(col_2)

#result of sum
print("The sum of the partx is:")
for i in range(len(matrix_1)):
    for j in range(len(matrix_1[0])):
        result[i][j] = matrix_1[i][j] + matrix_2[i][j]

for col_3 in result:
    print(col_3)

The martix_1 is:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
The matrix_2 is:
[10, 11, 12]
[13, 14, 15]
[16, 17, 19]
The sum of the partx is:
[11, 13, 15]
[17, 19, 21]
[23, 25, 28]


In [14]:
#subtraction of martix
matrix_1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
matrix_2 = [
    [10,11,12],
    [13,14,15],
    [16,17,19]
]
result = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

#result for addition subtraction and multiplication
print("The martix_1 is:")
for col_1 in matrix_1 :
    print(col_1)

print("The matrix_2 is:")
for col_2 in matrix_2:
    print(col_2)

#result of sum
print("The subtraction of the partx is:")
for i in range(len(matrix_1)):
    for j in range(len(matrix_1[0])):
        result[i][j] = matrix_1[i][j] - matrix_2[i][j]

for col_3 in result:
    print(col_3)

The martix_1 is:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
The matrix_2 is:
[10, 11, 12]
[13, 14, 15]
[16, 17, 19]
The subtraction of the partx is:
[-9, -9, -9]
[-9, -9, -9]
[-9, -9, -10]


In [16]:
#The addition of the matrix with numpy
import numpy as np

a = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])
b = np.array([
    [3,2,5],
    [3,3,4],
    [3,4,5]
])
print("The addition of matrix is")
addition = a + b 
print(addition)

[[ 4  4  8]
 [ 5  6  8]
 [ 6  8 10]]


In [ ]:
#The subtraction of the matrix with numpy
import numpy as np

a = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])
b = np.array([
    [3,2,5],
    [3,3,4],
    [3,4,5]
])
print("The subtraction of matrix is")
subtraction = a - b 
print(subtraction)